import json

with open('Trip_Planner_Assignment.ipynb', 'r', encoding='utf-8') as f:
    nb = json.load(f)

# ── Cell 1: Markdown header ───────────────────────────────────────────────────
md_header = {
    "cell_type": "markdown",
    "metadata": {},
    "source": [
        "## 14 · DeepEval Evaluation\n",
        "\n",
        "We use **DeepEval** to measure whether the multi-agent system produces *good* outputs — not just outputs that run without errors.\n",
        "\n",
        "| Metric | What it measures | Needs API key? |\n",
        "|--------|-----------------|----------------|\n",
        "| `BudgetAdherenceMetric` | Did the total cost stay within the user’s stated budget? | ❌ No |\n",
        "| `PreferenceMatchMetric` | Did the itinerary cover the user’s stated interests? | ❌ No |\n",
        "| `ItineraryCompletenessMetric` | Correct day count + headline + hotel + transport? | ❌ No |\n",
        "| `ReviewApprovalMetric` | Did `final_review_agent` approve the plan with zero issues? | ❌ No |\n",
        "| `AnswerRelevancyMetric` | Is the itinerary relevant to the original query? | ✅ Yes (OpenAI) |\n",
        "| `FaithfulnessMetric` | Does output stay faithful to retrieved data (no hallucinations)? | ✅ Yes (OpenAI) |\n",
        "\n",
        "> **Rule-based metrics (1–4) always run.** LLM-based metrics (5–6) are skipped if `OPENAI_API_KEY` is not set.\n"
    ]
}

# ── Cell 2: Custom metrics definition ────────────────────────────────────────
code_metrics = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "from deepeval.test_case import LLMTestCase\n",
        "from deepeval.metrics import AnswerRelevancyMetric, FaithfulnessMetric\n",
        "from deepeval.metrics.base_metric import BaseMetric\n",
        "\n",
        "\n",
        "# ── Custom Metric 1: Budget Adherence ────────────────────────────────────────\n",
        "class BudgetAdherenceMetric(BaseMetric):\n",
        "    \"\"\"Passes if the total cost does not exceed the user's stated budget.\"\"\"\n",
        "    def __init__(self):\n",
        "        self.name = 'Budget Adherence'\n",
        "        self.threshold = 1.0\n",
        "        self.score = 0.0\n",
        "        self.reason = ''\n",
        "        self.success = False\n",
        "\n",
        "    def measure(self, test_case: LLMTestCase) -> float:\n",
        "        meta   = test_case.additional_metadata or {}\n",
        "        total  = meta.get('total_cost', 0)\n",
        "        target = meta.get('target_budget', 1)\n",
        "        if target <= 0:\n",
        "            self.score, self.reason = 0.0, 'Target budget is zero or missing.'\n",
        "        elif total <= target:\n",
        "            self.score  = 1.0\n",
        "            self.reason = f'\\u2713 Under budget: \\u20b9{total:,} <= \\u20b9{target:,}'\n",
        "        else:\n",
        "            over_pct    = (total - target) / target * 100\n",
        "            self.score  = max(0.0, 1.0 - over_pct / 100)\n",
        "            self.reason = f'\\u2717 Over budget by {over_pct:.1f}%: \\u20b9{total:,} > \\u20b9{target:,}'\n",
        "        self.success = self.score >= self.threshold\n",
        "        return self.score\n",
        "\n",
        "    async def a_measure(self, test_case: LLMTestCase, *args, **kwargs) -> float:\n",
        "        return self.measure(test_case)\n",
        "\n",
        "    def is_successful(self) -> bool:\n",
        "        return self.success\n",
        "\n",
        "\n",
        "# ── Custom Metric 2: Preference Match ────────────────────────────────────────\n",
        "class PreferenceMatchMetric(BaseMetric):\n",
        "    \"\"\"Checks what fraction of the user's interests appear in the itinerary output.\"\"\"\n",
        "    def __init__(self, threshold: float = 0.5):\n",
        "        self.name = 'Preference Match'\n",
        "        self.threshold = threshold\n",
        "        self.score = 0.0\n",
        "        self.reason = ''\n",
        "        self.success = False\n",
        "\n",
        "    def measure(self, test_case: LLMTestCase) -> float:\n",
        "        meta      = test_case.additional_metadata or {}\n",
        "        interests = meta.get('interests', [])\n",
        "        output    = (test_case.actual_output or '').lower()\n",
        "        if not interests:\n",
        "            self.score, self.reason, self.success = 1.0, 'No interests specified.', True\n",
        "            return self.score\n",
        "        matched = [i for i in interests if i.lower() in output]\n",
        "        self.score  = len(matched) / len(interests)\n",
        "        missing     = list(set(interests) - set(matched))\n",
        "        self.reason = f'Matched {len(matched)}/{len(interests)}: {matched}' + (f' | Missing: {missing}' if missing else '')\n",
        "        self.success = self.score >= self.threshold\n",
        "        return self.score\n",
        "\n",
        "    async def a_measure(self, test_case: LLMTestCase, *args, **kwargs) -> float:\n",
        "        return self.measure(test_case)\n",
        "\n",
        "    def is_successful(self) -> bool:\n",
        "        return self.success\n",
        "\n",
        "\n",
        "# ── Custom Metric 3: Itinerary Completeness ──────────────────────────────────\n",
        "class ItineraryCompletenessMetric(BaseMetric):\n",
        "    \"\"\"Checks day count, headline, hotel, and transport are all present.\"\"\"\n",
        "    def __init__(self, threshold: float = 1.0):\n",
        "        self.name = 'Itinerary Completeness'\n",
        "        self.threshold = threshold\n",
        "        self.score = 0.0\n",
        "        self.reason = ''\n",
        "        self.success = False\n",
        "\n",
        "    def measure(self, test_case: LLMTestCase) -> float:\n",
        "        meta   = test_case.additional_metadata or {}\n",
        "        checks = {\n",
        "            'correct day count':  meta.get('expected_days', -1) == meta.get('actual_days', -2),\n",
        "            'headline present':   meta.get('has_headline', False),\n",
        "            'hotel selected':     meta.get('has_hotel', False),\n",
        "            'transport selected': meta.get('has_transport', False),\n",
        "        }\n",
        "        passed      = sum(checks.values())\n",
        "        self.score  = passed / len(checks)\n",
        "        failed      = [k for k, v in checks.items() if not v]\n",
        "        self.reason = f'{passed}/{len(checks)} checks passed.' + (f' Failed: {failed}' if failed else ' All OK \\u2713')\n",
        "        self.success = self.score >= self.threshold\n",
        "        return self.score\n",
        "\n",
        "    async def a_measure(self, test_case: LLMTestCase, *args, **kwargs) -> float:\n",
        "        return self.measure(test_case)\n",
        "\n",
        "    def is_successful(self) -> bool:\n",
        "        return self.success\n",
        "\n",
        "\n",
        "# ── Custom Metric 4: Review Approval ─────────────────────────────────────────\n",
        "class ReviewApprovalMetric(BaseMetric):\n",
        "    \"\"\"Passes if final_review_agent approved the plan with zero issues.\"\"\"\n",
        "    def __init__(self):\n",
        "        self.name = 'Review Approval'\n",
        "        self.threshold = 1.0\n",
        "        self.score = 0.0\n",
        "        self.reason = ''\n",
        "        self.success = False\n",
        "\n",
        "    def measure(self, test_case: LLMTestCase) -> float:\n",
        "        meta     = test_case.additional_metadata or {}\n",
        "        approved = meta.get('approved', False)\n",
        "        issues   = meta.get('issues', [])\n",
        "        if approved and not issues:\n",
        "            self.score, self.reason = 1.0, '\\u2713 Approved with no issues.'\n",
        "        elif approved:\n",
        "            self.score, self.reason = 0.7, f'Approved with {len(issues)} issue(s): {issues}'\n",
        "        else:\n",
        "            self.score, self.reason = 0.0, f'\\u2717 Not approved. Issues: {issues}'\n",
        "        self.success = self.score >= self.threshold\n",
        "        return self.score\n",
        "\n",
        "    async def a_measure(self, test_case: LLMTestCase, *args, **kwargs) -> float:\n",
        "        return self.measure(test_case)\n",
        "\n",
        "    def is_successful(self) -> bool:\n",
        "        return self.success\n",
        "\n",
        "\n",
        "print('\\u2713 4 custom DeepEval metrics defined (no API key required).')\n",
        "print('  1. BudgetAdherenceMetric        - total cost vs. stated budget')\n",
        "print('  2. PreferenceMatchMetric         - interests covered in itinerary')\n",
        "print('  3. ItineraryCompletenessMetric   - days + headline + hotel + transport')\n",
        "print('  4. ReviewApprovalMetric          - final_review_agent approved?')\n"
    ]
}

# ── Cell 3: Build test cases ──────────────────────────────────────────────────
code_testcases = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Build LLMTestCase objects from the executed workflow states ───────────────\n",
        "snap  = app.get_state(config={'configurable': {'thread_id': 'thread_demo_001'}}).values\n",
        "snap2 = app.get_state(config={'configurable': {'thread_id': 'thread_yours_002'}}).values\n",
        "\n",
        "\n",
        "def build_test_case(snap, label):\n",
        "    prefs  = snap['trip_preferences']\n",
        "    it     = snap['itinerary']\n",
        "    budget = snap['budget_summary']\n",
        "    review = snap['review_status']\n",
        "    hotel  = snap['hotel_data']\n",
        "    trans  = snap['transport_data']\n",
        "    places = snap['places_data']\n",
        "\n",
        "    # Human-readable output string for LLM-based metrics\n",
        "    actual_output = (\n",
        "        f\"Headline: {it['headline']}\\n\\n\"\n",
        "        + '\\n'.join(\n",
        "            f\"Day {d['day']}: Morning={d['morning']}, Afternoon={d['afternoon']}, Evening={d['evening']}\"\n",
        "            for d in it['days']\n",
        "        )\n",
        "        + f\"\\n\\nHotel: {hotel['top_pick']['name']} ({hotel['top_pick']['stars']}\\u2605, \"\n",
        "          f\"\\u20b9{hotel['top_pick']['price']:,}/night)\"\n",
        "        + f\"\\nTransport: {trans['recommended']['provider']} \"\n",
        "          f\"({trans['recommended']['mode']}, \\u20b9{trans['recommended']['price']:,})\"\n",
        "        + f\"\\nTotal: \\u20b9{budget['total']:,}  |  Budget: \\u20b9{budget['target']:,}\"\n",
        "    )\n",
        "\n",
        "    # Retrieval context = what the agents actually fetched from tools / memory\n",
        "    retrieval_context = [\n",
        "        f\"Weather summary: {snap['weather_data']['summary']}\",\n",
        "        f\"Hotels available: {[h['name'] for h in hotel['candidates']]}\",\n",
        "        f\"Transport options: {[o['provider'] + ' (' + o['mode'] + ')' for o in trans['options']]}\",\n",
        "        f\"Attractions: {[p['name'] for p in places['attractions']]}\",\n",
        "        f\"Memory recalled: {snap['user_profile']['recalled']}\",\n",
        "    ]\n",
        "\n",
        "    return LLMTestCase(\n",
        "        input=snap.get('raw_query', f\"{prefs['days']}-day trip to {prefs['destination']}\"),\n",
        "        actual_output=actual_output,\n",
        "        retrieval_context=retrieval_context,\n",
        "        additional_metadata={\n",
        "            'total_cost':     budget['total'],\n",
        "            'target_budget':  budget['target'],\n",
        "            'interests':      prefs['interests'],\n",
        "            'expected_days':  prefs['days'],\n",
        "            'actual_days':    len(it['days']),\n",
        "            'has_headline':   bool(it.get('headline')),\n",
        "            'has_hotel':      hotel.get('top_pick') is not None,\n",
        "            'has_transport':  bool(trans.get('recommended')),\n",
        "            'approved':       review['approved'],\n",
        "            'issues':         review['issues'],\n",
        "        }\n",
        "    )\n",
        "\n",
        "\n",
        "tc_demo  = build_test_case(snap,  'TC-1 Goa trip')\n",
        "tc_yours = build_test_case(snap2, 'TC-2 Your trip')\n",
        "\n",
        "print('Test cases built successfully:')\n",
        "print(f\"  TC-1 (Goa  ): input='{tc_demo.input[:70]}...'\")\n",
        "print(f\"  TC-2 (Yours): input='{tc_yours.input[:70]}...'\")\n"
    ]
}

# ── Cell 4: Run rule-based evaluations ───────────────────────────────────────
code_eval = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── Run all 4 rule-based metrics on both test cases ───────────────────────────\n",
        "from tabulate import tabulate\n",
        "\n",
        "test_cases = [\n",
        "    ('TC-1  Goa trip',  tc_demo),\n",
        "    ('TC-2  Your trip', tc_yours),\n",
        "]\n",
        "\n",
        "rows = []\n",
        "overall_pass = True\n",
        "\n",
        "for tc_name, tc in test_cases:\n",
        "    for MetricClass, kwargs in [\n",
        "        (BudgetAdherenceMetric,       {}),\n",
        "        (PreferenceMatchMetric,       {'threshold': 0.5}),\n",
        "        (ItineraryCompletenessMetric, {'threshold': 1.0}),\n",
        "        (ReviewApprovalMetric,        {}),\n",
        "    ]:\n",
        "        m     = MetricClass(**kwargs)\n",
        "        score = m.measure(tc)\n",
        "        passed = m.is_successful()\n",
        "        overall_pass = overall_pass and passed\n",
        "        rows.append([\n",
        "            tc_name,\n",
        "            m.name,\n",
        "            f'{score:.2f}',\n",
        "            f'{m.threshold:.2f}',\n",
        "            'PASS \\u2705' if passed else 'FAIL \\u274c',\n",
        "            (m.reason[:55] + '...') if len(m.reason) > 55 else m.reason,\n",
        "        ])\n",
        "\n",
        "headers = ['Test Case', 'Metric', 'Score', 'Thresh', 'Result', 'Reason']\n",
        "print(tabulate(rows, headers=headers, tablefmt='rounded_outline'))\n",
        "print()\n",
        "print('Overall:', '\\u2705 ALL PASSED' if overall_pass else '\\u26a0\\ufe0f  SOME METRICS FAILED')\n"
    ]
}

# ── Cell 5: LLM-based metrics (optional) ─────────────────────────────────────
code_llm = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── (Optional) LLM-based metrics — requires OPENAI_API_KEY ───────────────────\n",
        "# DeepEval uses GPT as a judge to score Answer Relevancy and Faithfulness.\n",
        "if USE_REAL_LLM:\n",
        "    from deepeval import evaluate\n",
        "    print('Running LLM-based metrics via OpenAI...')\n",
        "    evaluate(\n",
        "        test_cases=[tc_demo, tc_yours],\n",
        "        metrics=[\n",
        "            AnswerRelevancyMetric(threshold=0.7),\n",
        "            FaithfulnessMetric(threshold=0.7),\n",
        "        ]\n",
        "    )\n",
        "else:\n",
        "    print('OPENAI_API_KEY not set — LLM-based metrics skipped.')\n",
        "    print('Set it in your environment and re-run this cell to enable:\\n')\n",
        "    print('  Metric               Threshold  What it checks')\n",
        "    print('  AnswerRelevancyMetric   0.70     Is the itinerary relevant to the query?')\n",
        "    print('  FaithfulnessMetric      0.70     Does output use only retrieved data (no hallucinations)?')\n"
    ]
}

# ── Append all new cells to the notebook ─────────────────────────────────────
new_cells = [md_header, code_metrics, code_testcases, code_eval, code_llm]
nb['cells'].extend(new_cells)

with open('Trip_Planner_Assignment.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells (was 33).")
